server:
  port: 8000
  tomcat:
    uri-encoding: UTF-8
debug: false
spring:
  mail:
    host: smtp.163.com
    username: ipnet2018@163.com
    password: ipnet2018
    default-encoding: UTF-8
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML
    cache: false
    servlet:
      content-type: text/html
  resources:
    static-locations: classpath:/static/
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: mysql
    url: jdbc:mysql://localhost:3306/yummy?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=false
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    properties:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      hibernate:
        enable_lazy_load_no_trans: true
    open-in-view: true
  aop:
    auto: true
#  jackson:
#    date-format: yyyy-MM-dd
#    time-zone: GMT+8